services:
  qg-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis

  qg-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python server/worker_simulator.py
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
